



name: "Set Issue Label for issues from main QGIS repo"
on:
  issues:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: DelazJ/issue-action@v2.0.2
        with:
          title-or-body: "both"
          parameters: |
            [ {"keywords": ["QGIS version: 3.22"], "labels": ["3.22"], "milestone":"QGIS 3.22"},
              {"keywords": ["QGIS version: 3.24"], "labels": ["3.24"], "milestone":"QGIS 3.28"},
              {"keywords": ["QGIS version: 3.26"], "labels": ["3.26"], "milestone":"1"},
              {"keywords": ["QGIS version: 3.28"], "labels": ["3.28"], "milestone":"QGIS 3.28"}
            ]
          github-token: "${{ secrets.GITHUB_TOKEN }}"
