



name: "Set Issue Label for issues from main QGIS repo"
on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  test:
    permissions:
      issues: write

    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: Naturalclar/issue-action@dc881db370e1faa4bcc32ad5d3fadb6d905d8700 # v2.0.2
        with:
          title-or-body: "both"
          parameters: |
            [ {"keywords": ["QGIS version: 3.28"], "labels": ["3.28"]},
              {"keywords": ["QGIS version: 3.30"], "labels": ["3.30"]},
              {"keywords": ["QGIS version: 3.32"], "labels": ["3.32"]},
              {"keywords": ["QGIS version: 3.34"], "labels": ["3.34"]}
            ]
          github-token: "${{ secrets.GITHUB_TOKEN }}"
