name: "Set Issue Label for issues from main QGIS repo"
on:
  issues:
    types: [opened, reopened, closed]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "both"
          parameters: |
            [ {"keywords": ["QGIS version: 3.30"], "labels": ["3.20"]},
              {"keywords": ["QGIS version: 3.32"], "labels": ["3.22"]},
              {"keywords": ["QGIS version: 3.34"], "labels": ["3.24"]}
            ]
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Triage']
            })
            
  milestoning:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        activelabels: ["3.30", "3.32", "3.34"]
    steps:
      - id: echo-body
        run: echo '${{github.event.comment.body}}'
      - id: assign-milestone
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              milestone: 2
            })
            
  labelage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        activelabels: ["3.30", "3.32", "3.34"]
    steps:
      - id: echo-body
        run: echo '${{github.event.comment.body}}'
      
      - id: assign-labels
        uses: actions/github-script@v6
        if: contains(github.event.comment.body, 'QGIS version ${{ matrix.activelabels }}')
        with:
          #if: contains(github.event.comment.body, format('QGIS version{0} ${{ matrix.activelabels }}', ':'))
          script: |
            echo "contains(github.event.comment.body, format('QGIS version{0} ${{ matrix.activelabels }}', ':'))"
            echo '${{contains(github.event.comment.body, 'QGIS version: ${{ matrix.activelabels }}')}}'
            echo "${{contains(github.event.comment.body, 'QGIS version: ${{ matrix.activelabels }}')}}"
            echo `${{contains(github.event.comment.body, 'QGIS version: ${{ matrix.activelabels }}')}}`
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Feedback', '${{ matrix.activelabels }}' ]
            })

        #if: contains(github.event.comment.body, "QGIS version: 3.28")
#    if [[ contains(github.event.comment.body, "QGIS version: ${{ matrix.activelabels }}") ]]; then
