



name: "Set Issue Label for issues from main QGIS repo"
# Also add corresponding milestone to the issue
on:
  issues:
    types: [opened, reopened, closed]
env:
  MILESTONE: 2 # See https://api.github.com/repos/qgis/QGIS-Documentation/milestones
  BODY: ${{ github.event.issue.body }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        activelabels: ["3.30", "3.32", "3.34"]

    steps:
      - id: add_labels
        name: Assign Label
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Triage']
            })

      - id: add_labels_2
        name: Assign Label 2
        run: |
          LABEL=$(sed -r 's/^QGIS version: ([[:digit:]]\.[[:digit:]]+)/\1/' <<< ${{ env.BODY }}
          echo ${LABEL}
          
 #         SEARCH_STRING=$(echo "QGIS version: ${{ matrix.activelabels }}")
 #         echo "texte: $SEARCH_STRING"
 #         RECHERCHE=$(echo ${{ env.BODY }} | grep -c $SEARCH_STRING)
 #         echo "recherche: $RECHERCHE"
          
          
 #         if -z $RECHERCHE then;
 #           github.rest.issues.addLabels({
 #             issue_number: context.issue.number,
 #             owner: context.repo.owner,
 #             repo: context.repo.repo,
 #             labels: [${{ matrix.activelabels }}]
 #           })
 #         fi
