



name: "Set Issue Label for issues from main QGIS repo"
# Also add corresponding milestone to the issue
on:
  issues:
    types: [opened, reopened, closed]
env:
  MILESTONE: 2 # See https://api.github.com/repos/qgis/QGIS-Documentation/milestones
  BODY: "${{ github.event.issue.body }}"

jobs:

#  job1:
#    runs-on: ubuntu-latest
#    outputs:
#      versions: ${{ steps.set_versions.outputs.versions }}
#    steps:
#      - id: set_versions
#        run: |
#          VERSIONS=$(echo "[\"3.30\", \"3.32\", \"3.34\"]")
#          echo "versions=${VERSIONS}" >> $GITHUB_OUTPUT
     
  test:
    runs-on: ubuntu-latest
    # needs: job1
    steps:        

      - id: find_version_label
        name: Find Target version
        run: |
          LABEL=$(echo "${{ env.BODY }}" | sed -n -r "s/.*QGIS version: ([[:digit:]]\.[[:digit:]]+).*/\1/p")
          if [[ -z "${LABEL}" ]]; then
            echo "label=${LABEL}" >> $GITHUB_OUTPUT
          fi

      - id: assign_version
        name: Assign version Label
        if: ${{ steps.find_version_label.outputs.label }}
        uses: actions/github-script@v6
        with:
          script: |
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["${{ steps.find_version_label.outputs.label }}"]
              })

      - id: assign_milestone
        name: Assign milestone
        if: ${{ steps.find_version_label.outputs.label }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              milestone: ${{ env.MILESTONE }}
            })
