name: "Set Issue Label for issues from main QGIS repo"
on:
  issues:
    types: [opened, reopened, closed]
# env:
#   BODY: ${{ github.event.issue.body }} # comment.body semble inconnu
#   TITLE: ${{ github.event.issue.title }}
#   TEXTE: ${{ github.event.issue.body }}
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "both"
          parameters: |
            [ {"keywords": ["QGIS version: 3.30"], "labels": ["3.20"]},
              {"keywords": ["QGIS version: 3.32"], "labels": ["3.22"]},
              {"keywords": ["QGIS version: 3.34"], "labels": ["3.24"]}
            ]
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Triage']
            })
            
  milestoning:
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   matrix: 
    #     activelabels: ["3.30", "3.32", "3.34"]
    steps:
      - id: echo-body
        name: Return issue contents
        run: |
          echo ${{ github.event.issue.title }}
          echo ${{ github.event.issue.body }}
          
      - id: assign-milestone
        name: Assign milestone
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              milestone: 2
            })
            
  labelage:
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   matrix: 
    #     activelabels: ["3.30", "3.32", "3.34"]
    steps:
    

      # get the issue body
      - name: Get issue body as JSON
        id: get_issue_info
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: GET /repos/DelazJ/QGIS-Documentation/issues/{issue_number}/comments #{comment_id}
          issue_number: ${{ github.event.issue.number }}
          per_page: 1

      - id: find-version
        name: Find target version
        run: |
          echo ${{ github.event.issue.number }}
          VERSION=$(sed -r 's/^QGIS version: ([[:digit:]]\.[[:digit:]]+) .*/\1/p' "${{ github.event.issue.body }}")
          echo "la version est ${VERSION}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

# For example, contains(fromJSON('["push", "pull_request"]'), github.event_name) returns true if github.event_name is "push" or "pull_request"
# if: contains(fromJSON('["3.30", "3.32", "3.34"]'), ${{ version }})


      # # extract body from json output
      # - name: Get PR body as text
      #   id: get_pr_body
      #   uses: gr2m/get-json-paths-action@v1.x
      #   with:
      #     json: ${{ steps.get_pr_info.outputs.data }}
      #     body: "body"
      
      - id: assign-labels
        uses: actions/github-script@v6
        #if: contains(github.event.comment.body, "QGIS version ${{ matrix.activelabels }}")
        with:
          #if: contains(github.event.comment.body, format('QGIS version{0} ${{ matrix.activelabels }}', ':'))
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Feedback', '${{ steps.find-version.outputs.version }}' ]
            })

          # echo "contains(github.event.comment.body, format('QGIS version{0} ${{ matrix.activelabels }}', ':'))"
          # echo '${{contains(github.event.comment.body, 'QGIS version: ${{ matrix.activelabels }}')}}'
          # echo "${{contains(github.event.comment.body, 'QGIS version: ${{ matrix.activelabels }}')}}"
          # echo `${{contains(github.event.comment.body, 'QGIS version: ${{ matrix.activelabels }}')}}`
        #if: contains(github.event.comment.body, "QGIS version: 3.28")
#    if [[ contains(github.event.comment.body, "QGIS version: ${{ matrix.activelabels }}") ]]; then
