name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

permissions:
  contents: read

jobs:
  backport:

    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    name: Backport
    steps:
      - name: Backport Bot
        id: backport
        uses: m-kuhn/backport@7f3cab83e4b3b26aefcffda21851c3dc3d389f45  #v1.2.7
        with:
          github_token: ${{ secrets.BACKPORT_TOKEN }}
