name: HTML build with substitutions

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r REQUIREMENTS.txt
    - name: Build sphinx documentation
      run: |
          make html
    - name: Upload build artifact
      uses: actions/upload-artifact@v1
      with:
        name: HTML build
        path: build

  substitution_check:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r REQUIREMENTS.txt
    - uses: trilom/file-changes-action@v1.2.4
      id: changed_files
      with:
        output: ' '
        githubToken: ${{ secrets.GITHUB_TOKEN }}
    - name: Check substitutions
      run: python ./scripts/find_set_subst.py ${{ steps.changed_files.outputs.files_modified }} ${{ steps.changed_files.outputs.files_added }}

