name: Pull translations
# Download partially translated files from Transifex

on:
  schedule: #run at 23:00 on day-of-month 1 and 15
    - cron:  '0 23 1,15 * *'

  workflow_dispatch:

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  pull_translation:

    permissions:
      contents: write  # for Git to git push
    if: github.repository_owner == 'qgis'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # only pull to the translated branch
        target_branch: [release_3.28]
    env:
      TRANSIFEX_PASSWORD: ${{ secrets.TRANSIFEX_PASSWORD }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Check out repository
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      with:
        fetch-depth: 1
        ref: ${{ matrix.target_branch }}

    - name: Install Transifex client
      run: |
          curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
          mv tx LICENSE -t /usr/local/bin/

    - shell: bash
      name: create .transifexrc file
      run: |
        sudo echo -e "[https://www.transifex.com]\nrest_hostname = https://rest.api.transifex.com\ntoken = $TRANSIFEX_PASSWORD" > ~/.transifexrc

    - name: Download and sanitize files and folders
      run: bash ./scripts/minimize_translation.sh

#    - name: Show changes
#      run: echo `git status`

    - name: Load translations if any
      run: |
        git config --global user.name 'Transifex update'
        git config --global user.email 'tx-update@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        if git add locale/* && git commit -m "Loading new translations"; then
          git push
        else
         echo "no new translations"
        fi


#    - name: Pull source file using transifex client
 #     uses: transifex/cli-action@v1
  #    with:
   #       token: ${{ secrets.TRANSIFEX_PASSWORD }}
    #      args: pull --force --mode onlytranslated -l fr 

#    - name: Commit the changes in the PO files
 #     id: "auto-commit-action"
#      uses: stefanzweifel/git-auto-commit-action@v4
 #     with:
 #       commit_message: 'Load translated strings'

  #  - name: "Inform that changes have been made"
   #   if: steps.auto-commit-action.outputs.changes_detected == 'true'
    #  run: echo "Changes committed!"

#    - name: "Inform that no changes were performed"
 #     if: steps.auto-commit-action.outputs.changes_detected == 'false'
  #    run: echo "No Changes detected!"
