name: Translation statistics
# Pull statistics of translation in Transifex

on: 
  schedule:
    # runs tuesday at 6:00 UTC
    - cron: '0 6 * * 2'
  workflow_dispatch:

jobs:
  ReportTranslationStats:

    #if: github.repository_owner == 'qgis'
    runs-on: ubuntu-latest
    env:
      TRANSIFEX_PASSWORD: ${{ secrets.TRANSIFEX_PASSWORD }}
      BACKPORT_BRANCH: "release_3.28"

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7

    - name: Install dependencies
      run: python3 -m pip install requests

    - name: Report statistics
      run: python3 ./scripts/load_tx_stats.py $TRANSIFEX_PASSWORD

    - id: create_pr
      name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: Update statistics of translation
        title: Update statistics of translation
        delete-branch: true
        labels: |
          backport $BACKPORT_BRANCH
          Translation

    - name: Enable Pull Request Automerge
      run: gh pr merge --rebase --auto "${{ steps.create_pr.outputs.pull-request-number }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
